### PR TITLE
API rewrite in golang.

### PR DESCRIPTION
**Pull request by Shinyzenith**
* This is a draft PR, I'll make sure to ping the correct people once it's complete.
* I do want to preface this PR with the fact that I work full-time so progress might be slow at times but I will definitely get it done eventually!

TODO:
- [ ] Split logic into a logic package
- [ ] `api.go` aka the main file should only have the routing and call the handler functions from the logic package. 
- [ ] Split all global connections and contexts into a singleton pattern for uniform access.
- [ ] Figure out why net.ParseCDIR is failing for default prefix.
- [ ] Final cleanup before marking the PR as ready for review.

Signed-off-by: Shinyzenith <aakashsensharma@gmail.com>

### CODE REVIEW

**Comment by Shinyzenith** [comment]
I went with logrus as the logger, please do let me know if you guys would like some other package to handle logging.

**Comment by hamptonmoore** [comment]
I believe the daemons use zap, might be best to use the same logger between go services?

**Comment by Shinyzenith** [comment]
Alright, I'll use zap.

**Comment by Shinyzenith** [comment]
> The above ^ also goes for the connection context...should we use singleton pattern for it too?

Some interaction from anyone at team would help me to get along with the patch, making all the decisions alone might lead to unwanted design patterns which will lead to unnecessary refactors later.

**Comment by Shinyzenith** [comment]
@angelofallars feel free to join in since you're interested in working with me on the patch.

**Comment by angelofallars** [comment]
Yeah, I'll join in too!

**Comment by Shinyzenith** [comment]
Closing due to lack of interaction.

**Comment by mplscorwin** [comment]
You should consider forking the project.  Sorry that you didn't have more feedback from the devs on this.

**Pull request closed without merging**
