### PR TITLE
Add debugging/development utils

### PR DESCRIPTION
**Pull request by JcdeA**
This PR adds:
### CORS bypass proxy for development - powered by nginx (in docker), 
proxies /api to https://console.aarch64.com/api

### CODE REVIEW

**Comment by natesales** [comment]
This is way overkill in my opinion. We shouldn't bundle certificates or a nginx config purely for development. @hamptonmoore thoughts?

**Comment by JcdeA** [comment]
@natesales These are just dummy selfsigned certs, I could remove them if needed.

**Comment by hamptonmoore** [comment]
Hey! Thank you for the PR. This is a very interesting addition I’ve been meaning to do something like for a while. I agree with Nate and don’t think we should be committing keys even if they are just self signed dummies for this, maybe have them generated. It also doesn’t make much sense to have this compose if it doesn’t also launch docker and possibly even run the API & frontend? Those could all be mounted with volumes such that somebody can keep developing. I also would like to see the package lock uncommitted as you didn’t add any new NPM modules so it doesn’t make sense why it changed so much.

**Review by hamptonmoore — CHANGES_REQUESTED** [review]
explained in previous comment

**Comment by hamptonmoore** [comment]
Deprecated by recent docker work. Still interested in generation of self-signed certs to provide HTTPS access though

**Pull request closed without merging**
